version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running setup_env.py..."
      - python setup_env.py

artifacts:
  files:
    - "**/*"
