version: 0.2

cache:
  paths:
    - '/root/.cache/pip/**'  # Cache pip packages
    - '/root/.npm/**'         # Cache npm dependencies
    - '/root/.pyenv/**'

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running feature_store.py..."
      - python feature_store.py

artifacts:
  files:
    - "**/*"
