# config.yaml
region: "us-east-1"
sagemaker_execution_role: "arn:aws:iam::701586278703:role/service-role/AmazonSageMaker-ExecutionRole-20250214T203663"  # Update with your IAM role ARN
ecr_repository: "flight-delay-prediction-xgboost"   # ECR repository name
sagemaker_endpoint_name: "flight-delay-xgboost-endpoint-single-request"

bucket: "sagemaker-us-east-1-701586278703"
s3_csv_private_path: "s3://sagemaker-us-east-1-701586278703/airline-delay-cause/csv/"

# Athena configuration
athena_database: "db_airline_delay_cause"
database_name: "db_airline_delay_cause"
raw_table_name: "airline_delay_cause_csv_raw"
s3_staging_dir: "s3://sagemaker-us-east-1-701586278703/athena/staging"  # This will be created dynamically (e.g., s3://<bucket>/athena/staging)
dev_table_name: "development_data"
prod_table_name: "production_data"

# S3 paths and prefixes
s3_prefix: "flight-delay-prediction-xgboost"
feature_store_s3_dev: "s3://sagemaker-us-east-1-701586278703/feature-store/dev/"
feature_store_s3_prod: "s3://sagemaker-us-east-1-701586278703/feature-store/prod/"
dev_s3_uri: "s3://sagemaker-us-east-1-701586278703/feature-store/dev/"
prod_s3_uri: "s3://sagemaker-us-east-1-701586278703/feature-store/prod/"
dev_fg_name: "airline_delay_features_dev"
prod_fg_name: "airline_delay_features_prod"

baseline_model_metrics_json: "s3://sagemaker-us-east-1-701586278703/models/model_metrics.json"
baseline_model_pkl: "s3://sagemaker-us-east-1-701586278703/models/linear_regression_model.pkl"
xgboost_model: "s3://sagemaker-us-east-1-701586278703/xgboost_models/xgboost_model.tar.gz"
xgboost_model_metrics_json: "s3://sagemaker-us-east-1-701586278703/xgboost_models/model_metrics.json"
# Training hyperparameters for XGBoost
training:
  num_round: 100
  max_depth: 5
  eta: 0.2
  subsample: 0.8
  eval_metric: "auc"

# Monitoring configuration
monitoring:
  instance_type: "ml.m5.xlarge"
  instance_count: 1
  max_runtime_in_seconds: 3600
  schedule: "hourly"  # or a cron expression
